"""Export every flat part for the laser and the water-jet, and write CUT-LIST.md.

The parts live in cut-probe.scad, cut-housing.scad and cut-spectrum.scad; each lists its pieces
(piece = "list") with material, machine and quantity, so this script never keeps its own copy.
For every piece it renders each layer the piece has - "cut", "engrave", "engrave_back" - to

    ../fabrication/laser/<file>__<piece>.<layer>.svg   and .dxf   (laser: load both layers, cut last)
    ../fabrication/water-jet/<file>__<piece>.cut.dxf               (one part per file, mm - what services want)

    py export_cut.py                 # B0 rings for the water-jet (default)
    py export_cut.py --b0 laser      # B0 rings in 4 segments for the laser
    py export_cut.py --spectrum jet  # spectrum fins in 3 mm aluminium for the water-jet (default: laser)
    py export_cut.py --spectrum-style contours   # the spectrum as stacked contour layers instead of fins

Needs OpenSCAD (2021.01 or later) on PATH or in C:/Program Files/OpenSCAD.
"""

import argparse
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "fabrication"           # the exports live beside the sources, not among them
FILES = ["cut-probe", "cut-housing", "cut-spectrum"]
BASE = {"cut-probe": "probe", "cut-housing": "housing", "cut-spectrum": "spectrum"}   # the 3D file each includes
LAYERS = ["cut", "engrave", "engrave_back"]


def openscad():
    for c in [shutil.which("openscad"), "C:/Program Files/OpenSCAD/openscad.com", "C:/Program Files/OpenSCAD/openscad.exe"]:
        if c and Path(c).exists():
            return c
    raise SystemExit("OpenSCAD not found")


def run(scad, out, defs):
    """Render scad to out with -D defs; returns (ok, stderr)."""
    args = [OPENSCAD, "-o", str(out)]
    for k, v in defs.items():
        args += ["-D", f'{k}={v}']
    p = subprocess.run(args + [str(HERE / f"{scad}.scad")], capture_output=True, text=True, cwd=HERE)
    return p.returncode == 0 and out.exists() and out.stat().st_size > 0, p.stderr


def echoes(scad, defs):
    with tempfile.TemporaryDirectory() as d:
        out = Path(d) / "x.echo"
        run(scad, out, defs)
        return [m.group(1) for m in re.finditer(r'^ECHO: "(.*)"$', out.read_text(encoding="utf-8"), re.M)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--b0", choices=["jet", "laser"], default="jet")
    ap.add_argument("--spectrum", choices=["laser", "jet"], default="laser")
    ap.add_argument("--spectrum-style", choices=["fins", "contours"], default="fins")
    a = ap.parse_args()
    common = {"b0_process": f'"{a.b0}"', "spec_process": f'"{a.spectrum}"', "style": f'"{a.spectrum_style}"'}
    for d in ["laser", "water-jet"]:
        (OUT / d).mkdir(parents=True, exist_ok=True)
        for f in (OUT / d).glob("*"):
            f.unlink()

    rows, checks = [], {}
    for scad in FILES:
        base = set(echoes(BASE[scad], {"part": '"none"'}))           # the 3D file's own echoes, not repeated here
        lines = echoes(scad, {**common, "piece": '"list"'})
        checks[scad] = [l for l in lines if not l.startswith("PIECE|") and l not in base]
        for l in lines:
            if not l.startswith("PIECE|"):
                continue
            f = l.split("|")
            name, material, machine, qty = f[1], f[2], f[3], f[4]
            note = f[5] if len(f) > 5 else ""
            defs = dict(common, layer='"cut"')
            m = re.fullmatch(r"([a-z_]+?)(\d+)", name)                 # fin3, layer7: piece + idx
            if m:
                defs.update(piece=f'"{m.group(1)}"', idx=m.group(2))
            else:
                defs["piece"] = f'"{name}"'
            folder = OUT / ("water-jet" if machine == "water-jet" else "laser")
            made = []
            for layer in LAYERS:
                if machine == "water-jet" and layer != "cut":
                    continue                                          # a water-jet does not engrave
                defs["layer"] = f'"{layer}"'
                for ext in (["dxf"] if machine == "water-jet" else ["svg", "dxf"]):
                    out = folder / f"{scad}__{name}.{layer}.{ext}"
                    ok, err = run(scad, out, defs)
                    if not ok:
                        out.unlink(missing_ok=True)
                        if err.strip() and "empty" not in err.lower():
                            raise SystemExit(f"{out.name}: {err}")
                        break                                         # this piece has no such layer
                    made.append(out.relative_to(OUT).as_posix())
            rows.append((scad, name, qty, material, machine, note, made))
            print(f"{scad:13} {name:16} x{qty:>3}  {machine:9} {len(made)} files")

    write_list(rows, checks, a.b0)


def write_list(rows, checks, b0):
    md = ["# Cut list", "",
          f"Generated by `py export_cut.py{' --b0 laser' if b0 == 'laser' else ''}` from cut-probe.scad, cut-housing.scad and",
          "cut-spectrum.scad - do not edit; change the .scad files (machine and sheet settings: cut-common.scad) and re-run.", "",
          "## Before cutting", "",
          "- **Laser** (CO2, kerf 0.15 mm compensated in the files): acrylic only. Never PVC (chlorine gas), polycarbonate",
          "  (burns) or ABS. Load the `.engrave` file as a raster/fill layer and the `.cut` file as a vector cut, engrave",
          "  first, cut last. `.engrave_back`: cut the part, flip it about its vertical axis in the bed, align, engrave",
          "  (the file is already mirrored) - 1.2 mm deep for the housing cover's optocoupler pockets.",
          "- **Water-jet** (kerf 0.9 mm compensated): send the `.cut.dxf` files, mm, one part per file, with the quantity",
          "  below. No hole is below 6 mm. Ask for no taper compensation; the faces only need to be flat.",
          "- **Cut the test first:** one `cradle_saddle` and one housing `washer` - check the slot fit and the M3 holes on",
          "  your machine; change `laser_kerf` / `cut_fit` in cut-common.scad if they are loose or tight.", "",
          "## Parts", "",
          "| File | Piece | Qty | Material | Machine | Files |", "|---|---|---|---|---|---|"]
    for scad, name, qty, material, machine, note, made in rows:
        files = "<br>".join(f"`{Path(m).name}`" for m in made)
        md.append(f"| {scad} | {name}{' (' + note + ')' if note else ''} | {qty} | {material} | {machine} | {files} |")
    md += ["", "## Bought, not cut", "",
           "- Former: acrylic or PVC tube 40 x 2 mm, 125 mm long (cut by saw, not laser). Sleeve: acrylic tube 35 x 2 mm, 125 mm.",
           "- Coil: AWG26 enamelled wire, 60 m (51 m needed). B0 pair: AWG16, 2 x 392 m (784 m, about 9.2 kg).",
           "- Nylon: M4 or M6 threaded rod + nuts for the B0 stacks (8 per coil, M6 for the water-jet rings), M3 screws for the cradle.",
           "- Brass 1/4\"-20 nut (tripod). Housing: M3x12 x 4 (top), M3x10 + M3 nut x 8 (plate). Solvent cement for acrylic.",
           "", "## Checks (from the .scad files)", ""]
    for scad, lines in checks.items():
        md += [f"**{scad}**", ""] + [f"- {l}" for l in lines] + [""]
    (OUT / "CUT-LIST.md").write_text("\n".join(md), encoding="utf-8")
    print("CUT-LIST.md written")


OPENSCAD = openscad()
if __name__ == "__main__":
    main()
